# Generated by Django 6.0.3 on 2026-03-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_date', models.DateField()),
                ('odometer_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liters', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cost_per_liter', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_full_tank', models.BooleanField(default=True)),
                ('fuel_station', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_efficiency_km_per_liter', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('cost_per_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Fuel Refill',
                'verbose_name_plural': 'Fuel Refills',
                'ordering': ['-refill_date', '-odometer_km'],
            },
        ),
        migrations.CreateModel(
            name='OdometerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Odometer Log',
                'verbose_name_plural': 'Odometer Logs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_odometer_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_odometer_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-start_at'],
            },
        ),
    ]
