# Generated by Django 6.0.3 on 2026-03-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mileage', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrefill',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_refills', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='odometerlog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_logs', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle'),
        ),
    ]
