# Generated by Django 6.0.3 on 2026-03-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for the mobile app', max_length=50)),
                ('is_system', models.BooleanField(default=True, help_text='System-defined categories cannot be deleted')),
            ],
            options={
                'verbose_name': 'Maintenance Category',
                'verbose_name_plural': 'Maintenance Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(choices=[('time', 'Time Interval'), ('mileage', 'Mileage Interval'), ('both', 'Time and Mileage')], default='both', max_length=20)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('interval_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_odometer_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('completed', 'Completed'), ('snoozed', 'Snoozed')], default='active', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Reminder',
                'verbose_name_plural': 'Maintenance Reminders',
                'ordering': ['due_date', 'due_odometer_km'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_date', models.DateField()),
                ('odometer_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='maintenance/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='maintenance.maintenancecategory')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-service_date', '-odometer_km'],
            },
        ),
    ]
