# Generated by Django 6.0.3 on 2026-03-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='maintenancereminder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancecategory'),
        ),
        migrations.AddField(
            model_name='maintenancereminder',
            name='last_record',
            field=models.ForeignKey(blank=True, help_text='The maintenance record this reminder is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='maintenancereminder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='vehicles.vehicle'),
        ),
    ]
