# Generated by Django 6.0.3 on 2026-03-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('maintenance_prediction', 'Maintenance Prediction'), ('fuel_efficiency', 'Fuel Efficiency'), ('cost_analysis', 'Cost Analysis'), ('health_score', 'Vehicle Health Score'), ('recommendation', 'General Recommendation')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('detail', models.TextField(blank=True, help_text='Detailed explanation and reasoning')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence 0.0 to 1.0', null=True)),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Input data used to generate insight')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Overall health score 0 to 100')),
                ('maintenance_score', models.FloatField(blank=True, null=True)),
                ('mileage_score', models.FloatField(blank=True, null=True)),
                ('fuel_score', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Vehicle Health Score',
                'ordering': ['-computed_at'],
            },
        ),
    ]
